# Generated by Django 3.1.3 on 2021-01-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=1000)),
                ('attachment', models.CharField(max_length=300)),
                ('parent_comment_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='findings',
            fields=[
                ('finding_id', models.AutoField(primary_key=True, serialize=False)),
                ('finding_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('permalink', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=30)),
                ('icon_file_name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='findings_ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('user', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.PositiveIntegerField()),
                ('downvotes', models.PositiveIntegerField()),
                ('finding_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakop_app.findings')),
            ],
        ),
        migrations.AddField(
            model_name='findings',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakop_app.tags'),
        ),
        migrations.AddField(
            model_name='findings',
            name='user_id',
            field=models.ForeignKey(on_delete=models.SET('Deleted'), to='zakop_app.users'),
        ),
        migrations.CreateModel(
            name='comments_ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField()),
                ('user', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.PositiveIntegerField()),
                ('downvotes', models.PositiveIntegerField()),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakop_app.comments')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='finding_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakop_app.findings'),
        ),
    ]
