# Generated by Django 3.1.3 on 2021-01-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zakop_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameModel(
            old_name='comments_ratings',
            new_name='comments_rating',
        ),
        migrations.RenameModel(
            old_name='findings',
            new_name='finding',
        ),
        migrations.RenameModel(
            old_name='findings_ratings',
            new_name='findings_rating',
        ),
        migrations.RenameModel(
            old_name='tags',
            new_name='tag',
        ),
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='comments_rating',
            options={'verbose_name_plural': 'comments_ratings'},
        ),
        migrations.AlterModelOptions(
            name='finding',
            options={'verbose_name_plural': 'findings'},
        ),
        migrations.AlterModelOptions(
            name='findings_rating',
            options={'verbose_name_plural': 'finding_ratings'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'tags'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'users'},
        ),
    ]
