# Generated by Django 3.1.3 on 2021-02-23 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zakop_app', '0002_auto_20210122_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_rating',
            name='user',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='finding',
            name='tag_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='zakop_app.tag'),
        ),
        migrations.AlterField(
            model_name='findings_rating',
            name='user',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
