# Generated by Django 3.1.3 on 2021-02-23 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zakop_app', '0004_auto_20210223_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='user_id',
            field=models.ForeignKey(on_delete=models.SET('Deleted'), to=settings.AUTH_USER_MODEL),
        ),
    ]
