# Generated by Django 3.1.3 on 2021-02-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zakop_app', '0005_auto_20210223_1351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments_rating',
            new_name='CommentsRating',
        ),
        migrations.RenameModel(
            old_name='findings_rating',
            new_name='FindingRating',
        ),
        migrations.RenameModel(
            old_name='user',
            new_name='ZakopUser',
        ),
    ]
